[package]
name = "sort-tricks"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
ordered-float = { version = "3.0", optional = true }

[dev-dependencies]
ordered-float = { version = "3.0", features = ["proptest"] }
proptest = "1"
